### ISSUE TITLE
Cannot get GraphiQL to send/display requests

### ISSUE THREAD

**Issue by sulliwane** [kadirahq/graphql-blog-schema#4]
Hello,
following the tutorial, I can't get Graphiql to work.

On a remote server, I forked this repo, then `git checkout server-side-schema`, then `npm install`, updated the **server/schema.js** according to the instructions, and finally `npm start`.

The port 3000 is open on the machine, and when I open **112.74.106.164:3000/graphql** in the browser, graphiql is loaded. But nothing happen on graphql request. I tried this Query:

```
{
  authors {
    name
  }
}
```

and this mutation:

```
mutation _ {
  createAuthor(
    _id: "john",
    name: "John Carter"
  ) {
    name
  }
}
```

Mongodb is running well, and both of these request work if I run them directly from the serve. But no chance through Graphiql...

Any help would be much appreciated, Thanks.

Here is my **server.js** (unchanged):

```
require('babel/register');
var express = require('express');
var graphql = require('graphql');
var expressGraphql = require('express-graphql');
var Schema = require('./server/schema.js');

var app = express();

app.use('/', expressGraphql({
  schema: Schema,
  graphiql: true
}));

app.listen(3000);
console.log('GraphQL Sandbox started on port: 3000');
```

And here is the **schema.js**:

```
const mongo = require('promised-mongo');
// You can use any MONGO_URL here, whether it's locally or on cloud.
const db = mongo('mongodb://localhost/mydb');
const authorsCollection = db.collection('authors');

import * as _ from 'underscore';

import {
  GraphQLList,
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLString,
  GraphQLInt,
  GraphQLFloat,
  GraphQLEnumType,
  GraphQLNonNull
} from 'graphql';

const Author = new GraphQLObjectType({
  name: 'Author',
  description: 'Represent the type of an author of a blog post or a comment',
  fields: () => ({
    _id: {type: GraphQLString},
    name: {type: GraphQLString},
    twitterHandle: {type: GraphQLString}
  })
});

const Query = new GraphQLObjectType({
  name: 'RootQuery',
  fields: {
    authors: {
      type: new GraphQLList(Author),
      resolve: function() {
        return authorsCollection.find().toArray();
      }
    }
  }
});
const Mutation = new GraphQLObjectType({
  name: 'Mutations',
  fields: {
    createAuthor: {
      type: Author,
      args: { 
        _id: {type: new GraphQLNonNull(GraphQLString)},
        name: {type: new GraphQLNonNull(GraphQLString)},
        twitterHandle: {type: GraphQLString}
      },
      resolve: function(rootValue, args) {
        let author = _.clone(args);
        return authorsCollection.insert(author)
          .then(_ => author);
      }
    }
  }
});

const Schema = new GraphQLSchema({
  query: Query,
  mutation: Mutation
}); 

export default Schema;
```

**Comment by arunoda** [comment]
Quite not sure about the issue. I suspect, it's something with the client side GraphiQL code.
Check this todo app: https://github.com/kadira-samples/react-graphql-todos

I'm running it on a production server without any issues.

**Comment by sulliwane** [comment]
Thanks for your answer. I checked your app, but looks there is no use of GraphiQL, which I'd like to have for testing purpose during the dev :(

I just tried POST request with POSTMAN {query:authors{name}}, and it works. So indeed, it is a problem on the GraphiQL side...

How did you implement https://sandbox.learngraphql.com/ ?

**Comment by arunoda** [comment]
It's Scheme is on the client. There is not talking back and forth with the
server.

**Comment by sulliwane** [comment]
Ok. Thanks for your feedback. I'll post if I find the solution

**Comment by sulliwane** [comment]
The problem is related with firefox as I have no problem sending request through Graphiql if it's opened in Opera or Chrome

**Comment by projectdragonscale** [comment]
i have the save problem. did you lately install xampp or mongoose lately? i am suspecting that is my problem
